# Generated by Django 5.0.6 on 2024-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_menu_offer_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='des',
            field=models.TextField(),
        ),
    ]
